### ISSUE TITLE
`cargo-recursive-clean` panics when encountering unwalkable directory

### ISSUE THREAD

**Issue by hankjordan** [OLoKo64/cargo-recursive-clean#1]
```
Failed to read entry: WalkError { depth: 8, kind: Io { path: Some("< ... snip ... >"), error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } } }
```

This should display a warning and continue execution instead of panicking

**Comment by oloko64** [comment]
Thanks for reporting the issue.

It should be fixed in version `0.2.310`, when encountering a error during walk it now prints the error, not panicking.
